language: node_js
node_js:
 - "8"

branches:
 only:
  - develop

before_install:
- npm config set //registry.npmjs.org/:_authToken $NPM_API_KEY

install:
- npm install

scripts:
- npm run-script compile
- npm run-script generate

deploy:
  provider: npm
  email: "brainenjii@gmail.com"
  api_key: "$NPM_API_KEY"
